sudo: required

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull binout/docker-asciidoctor-deckjs

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-deckjs binout/docker-asciidoctor-deckjs asciidoctor -T /asciidoctor-backends/haml/deckjs -D /documents/output *.adoc

after_error:
  - docker logs asciidoc-to-deckjs

after_failure:
  - docker logs asciidoc-to-deckjs

after_success:
  - cd output ; sed 's/"\/\/cdnjs/"https:\/\/cdnjs/'  README.html > index.html ; cp -R ../images images
  - mkdir deck.js ; curl -LkSs https://github.com/imakewebthings/deck.js/archive/1.1.0.tar.gz | tar xfz - -C deck.js --strip-components=1
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
